title: Windows Security Event Log Cleared
status: experimental
description: Detects when the Windows Security eventlog has been cleared by looking for event id 1102.
author: Josh Brower
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 1102
    condition: selection
falsepositives:
    - None
fields:
    - SubjectUsername
level: high
